name: TF PR validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: src/
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          # renovate: datasource=github-releases depName=hashicorp/terraform versioning=hashicorp
          terraform_version: 1.10.5