name: TF PR validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: src/
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          # renovate: datasource=github-releases depName=hashicorp/terraform versioning=hashicorp
          terraform_version: 1.9.5