name: TF PR validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: src/
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          # renovate: datasource=github-releases depName=hashicorp/terraform versioning=hashicorp
          terraform_version: 1.10.5